In [4]:
# Basic ndarrays
import numpy as np

#Uses numbers 0-15 and resizes it to 3 rows, 5 columns
# OR 3 lists of 5 elements. Arange reuturns an array
a = np.arange(15).reshape(3,5)
print(a)

#Some Basic properties
print("\nDimensionality: {}".format(a.ndim))
print("Shape: {}".format(a.shape))
print("Size: {}\n".format(a.size))

#String Containing data type
a.dtype.name

#Creating 2D arrays manually. Sequence of 1D arrays
ab = np.array(([21,5,2,4],[1,8,5,3]), dtype='float32')
print(ab)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Dimensionality: 2
Shape: (3, 5)
Size: 15

[[21.  5.  2.  4.]
 [ 1.  8.  5.  3.]]


In [38]:
#Slicing
t = np.arange(0,10)
print(t[:2])     # First two
print(t[2:])     # Omit first two
print(t[-2:])    # Last two
print(t[:-2])    # Omit last two
print(t[::-1])   # Reverse order
print(t[::2])    # Every even-th element
print(t[1::2])   # Every odd-th element
print(t[2:7:3])  # Every 3rd element between elements 2 and 7

#2D slicing
def f(x,y):
    return 1.5*y**2+3*x

m = np.fromfunction(f, (3,8)) # Creates 2D matrix from function
print()
print(m)
print()
print(m[1,3])    # Row 1, column 3
print(m[2])      # 3rd Row
print(m[:,0])    # First column
print(m[..., 3]) # 4th column. "..." is used in place of many :'s
# Note that interations are done over the first axis (rows)

[0 1]
[2 3 4 5 6 7 8 9]
[8 9]
[0 1 2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]
[0 2 4 6 8]
[1 3 5 7 9]
[2 5]

[[ 0.   1.5  6.  13.5 24.  37.5 54.  73.5]
 [ 3.   4.5  9.  16.5 27.  40.5 57.  76.5]
 [ 6.   7.5 12.  19.5 30.  43.5 60.  79.5]]

16.5
[ 6.   7.5 12.  19.5 30.  43.5 60.  79.5]
[0. 3. 6.]
[13.5 16.5 19.5]


In [49]:
# Shape Manipulation
print(m.shape)         # Dimensions of matrix
print()
print(m.ravel())       # Flattens matrix to a 1D vector
print()
print(m.reshape(4,6))  # Reshapes matrix. Goes in order of the rows. 
print()
m.resize(6,4)          # Use resize function to modify in place. 
print(m)
print()
print(m.T)             # Transpose
print()
print(m.reshape(3,-1)) # Automatically calculate missing dimension


(6, 4)

[ 0.   1.5  6.  13.5 24.  37.5 54.  73.5  3.   4.5  9.  16.5 27.  40.5
 57.  76.5  6.   7.5 12.  19.5 30.  43.5 60.  79.5]

[[ 0.   1.5  6.  13.5 24.  37.5]
 [54.  73.5  3.   4.5  9.  16.5]
 [27.  40.5 57.  76.5  6.   7.5]
 [12.  19.5 30.  43.5 60.  79.5]]

[[ 0.   1.5  6.  13.5]
 [24.  37.5 54.  73.5]
 [ 3.   4.5  9.  16.5]
 [27.  40.5 57.  76.5]
 [ 6.   7.5 12.  19.5]
 [30.  43.5 60.  79.5]]

[[ 0.  24.   3.  27.   6.  30. ]
 [ 1.5 37.5  4.5 40.5  7.5 43.5]
 [ 6.  54.   9.  57.  12.  60. ]
 [13.5 73.5 16.5 76.5 19.5 79.5]]

[[ 0.   1.5  6.  13.5 24.  37.5 54.  73.5]
 [ 3.   4.5  9.  16.5 27.  40.5 57.  76.5]
 [ 6.   7.5 12.  19.5 30.  43.5 60.  79.5]]


In [27]:
# Linspace function. Used for floating-point sequences to get exact number in sequence. 
# 9 numbers between 0 and 2pi (so pi/4 increments)
np.linspace(0, 2*np.pi, 9)
print(np.linspace(0, 10, 5))
print(np.arange(0, 10.1, 2.5))

[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]


In [50]:
#Arithmetic: 
# Done element-wise

a = np.array([1,2,3,4])
print(a + 4.1)
print(a**3)
print(a + 2*a**2)

b = np.array([10, 1, 0, -1])
print(a*b)

#Combine 2 arrays
np.concatenate((a,b))

# Functions from ndarray
print(a.sum())
print(sum(a))

ab.sum(axis=1) # Row Sums
ab.sum(axis=0) # Column sums

# Cumulative sums
print(ab.cumsum())       #Unwinds whole array
print(ab.cumsum(axis=1)) # Cumulative sum along the rows

[5.1 6.1 7.1 8.1]
[ 1  8 27 64]
[ 3 10 21 36]
[10  2  0 -4]
10
10
[21. 26. 28. 32. 33. 41. 46. 49.]
[[21. 26. 28. 32.]
 [ 1.  9. 14. 17.]]


In [68]:
# Repeat Funciton

#Array of Zeros
np.zeros((2,3))

np.repeat(1, 20).reshape(4,5) 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [70]:
#Math

# euler's number
np.exp(1)

# sin/cos
np.sin(np.pi)

1.2246467991473532e-16