In [1]:
# Basic ndarrays
import numpy as np

#Uses numbers 0-15 and resizes it to 3 rows, 5 columns
# OR 3 lists of 5 elements. Arange reuturns an array
a = np.arange(15).reshape(3,5)
print(a)

#Some Basic properties
print("\nDimensionality: {}".format(a.ndim))
print("Shape: {}".format(a.shape))
print("Size: {}\n".format(a.size))

#String Containing data type
a.dtype.name

#Creating 2D arrays manually. Sequence of 1D arrays
ab = np.array(([21,5,2,4],[1,8,5,3]), dtype='float32')
print(ab)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Dimensionality: 2
Shape: (3, 5)
Size: 15

[[21.  5.  2.  4.]
 [ 1.  8.  5.  3.]]


In [43]:
#Slicing
t = np.arange(0,10)
print(t[:2])              # First two
print(t[2:])              # Omit first two
print(t[-2:])             # Last two
print(t[:-2])             # Omit last two
print(t[::-1])            # Reverse order
print(t[::2])             # Every even-th element
print(t[1::2])            # Every odd-th element
print(t[2:7:3])           # Every 3rd element between elements 2 and 7
print(t[[[1,4,2,9]]])     # Custom slicing
print(t[[True, False]*5]) # Boolean indexing

print(t[np.array([[1,3], [6,7]])]) # Can also index to form a matrix

#2D slicing
def f(x,y):
    return 1.5*y**2+3*x

m = np.fromfunction(f, (3,8)) # Creates 2D matrix from function
print()
print(m)
print()
print(m[1,3])    # Row 1, column 3
print(m[2])      # 3rd Row
print(m[:,0])    # First column
print(m[..., 3]) # 4th column. "..." is used in place of many :'s

# Fancy Subsetting: Only rows with a 6 in them, only columns with a mean over 20
r = [6 in x for x in m]
c = [np.mean(m[:,x]) > 20 for x in range(m.shape[1])] 
print()
print(m[:,c][r])
# print(m[[6 in x for x in m], [np.mean(m[:,x]) > 20 for x in range(m.shape[1])]] )


[0 1]
[2 3 4 5 6 7 8 9]
[8 9]
[0 1 2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]
[0 2 4 6 8]
[1 3 5 7 9]
[2 5]
[1 4 2 9]
[0 2 4 6 8]
[[1 3]
 [6 7]]

[[ 0.   1.5  6.  13.5 24.  37.5 54.  73.5]
 [ 3.   4.5  9.  16.5 27.  40.5 57.  76.5]
 [ 6.   7.5 12.  19.5 30.  43.5 60.  79.5]]

16.5
[ 6.   7.5 12.  19.5 30.  43.5 60.  79.5]
[0. 3. 6.]
[13.5 16.5 19.5]

[[24.  37.5 54.  73.5]
 [30.  43.5 60.  79.5]]


In [49]:
# Shape Manipulation
print(m.shape)         # Dimensions of matrix
print()
print(m.ravel())       # Flattens matrix to a 1D vector
print()
print(m.reshape(4,6))  # Reshapes matrix. Goes in order of the rows. 
print()
m.resize(6,4)          # Use resize function to modify in place. 
print(m)
print()
print(m.T)             # Transpose
print()
print(m.reshape(3,-1)) # Automatically calculate missing dimension


(6, 4)

[ 0.   1.5  6.  13.5 24.  37.5 54.  73.5  3.   4.5  9.  16.5 27.  40.5
 57.  76.5  6.   7.5 12.  19.5 30.  43.5 60.  79.5]

[[ 0.   1.5  6.  13.5 24.  37.5]
 [54.  73.5  3.   4.5  9.  16.5]
 [27.  40.5 57.  76.5  6.   7.5]
 [12.  19.5 30.  43.5 60.  79.5]]

[[ 0.   1.5  6.  13.5]
 [24.  37.5 54.  73.5]
 [ 3.   4.5  9.  16.5]
 [27.  40.5 57.  76.5]
 [ 6.   7.5 12.  19.5]
 [30.  43.5 60.  79.5]]

[[ 0.  24.   3.  27.   6.  30. ]
 [ 1.5 37.5  4.5 40.5  7.5 43.5]
 [ 6.  54.   9.  57.  12.  60. ]
 [13.5 73.5 16.5 76.5 19.5 79.5]]

[[ 0.   1.5  6.  13.5 24.  37.5 54.  73.5]
 [ 3.   4.5  9.  16.5 27.  40.5 57.  76.5]
 [ 6.   7.5 12.  19.5 30.  43.5 60.  79.5]]


In [50]:
#Arithmetic: 
# Done element-wise like in R

a = np.array([1,2,3,4])
print(a + 4.1)
print(a**3)
print(a + 2*a**2)

b = np.array([10, 1, 0, -1])
print(a*b)

# Functions from ndarray
print(a.sum())
print(sum(a))

ab.sum(axis=1) # Row Sums
ab.sum(axis=0) # Column sums

# Cumulative sums
print(ab.cumsum())       #Unwinds whole array
print(ab.cumsum(axis=1)) # Cumulative sum along the rows

[5.1 6.1 7.1 8.1]
[ 1  8 27 64]
[ 3 10 21 36]
[10  2  0 -4]
10
10
[21. 26. 28. 32. 33. 41. 46. 49.]
[[21. 26. 28. 32.]
 [ 1.  9. 14. 17.]]


In [33]:
# Stacking ( R: Cbind and Rbind )
r = np.zeros((3,4))
s = np.ones((5,4))
print(np.vstack((r,s))) # Vstack = rbind. Binds along 0th axis
print()

t = np.ones((3, 2))
print(np.hstack((r,t))) # hstack = cbind. Binds along 1st axis
print()

# For 1D vectors:
r1 = np.array([1,4,8,2])
r2 = np.array([5,9,1,4])
r3 = np.array(['Dog',"car","cheese",'red'])
np.column_stack((r1,r2)) # cbinds 1D vectors into 2 columns. Use row_stack to rbind 1D vectors
np.column_stack((r1,r3)) # However, they must be the same type

from numpy import newaxis
print(r1.T)              # This doesn't work
print(r1[:, newaxis])    # Turns it into a column vector
print()

# Concatenation
print(np.concatenate((r1, r2)))      # Combines 1D vectors
print()
print(np.concatenate((r,s)))         # Note this just rbinds
print() 
print(np.concatenate((r,t), axis=1)) # This cbinds

# Custom Splitting
np.vsplit(np.ones((4,4)),4)          # Splits matrix into 4 rows

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1.]]

[1 4 8 2]
[[1]
 [4]
 [8]
 [2]]

[1 4 8 2 5 9 1 4]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 1.]]


[array([[1., 1., 1., 1.]]),
 array([[1., 1., 1., 1.]]),
 array([[1., 1., 1., 1.]]),
 array([[1., 1., 1., 1.]])]

In [9]:
# Broadcasting
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])         # We want to add this to each row

vv = np.tile(v, (4, 1))         # This stacks the vector in 4 rows and 1 column. Can modify columns to repeat it.
print(vv)
print()
print(x + vv)
# Note that numpy will automatically do this (broadcasting)
print(x+v)
print()
# Adding columns. Transposing is easiest
w = np.array([5,1,5,1])
print((x.T + w).T)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

[[ 6  7  8]
 [ 5  6  7]
 [12 13 14]
 [11 12 13]]


In [26]:
# Dictionaries. Use {key : value}
cubes = {x : x**3 for x in range(10)}     # Dict comprehensions
print(cubes)

cubes[3]
print(7 in cubes) # Note this only works for the keys
cubes[10] = 10**3 # Adds 10 to the dictionary

cubes.keys()
cubes.values()
list(cubes.items())

{0: 0, 1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343, 8: 512, 9: 729}
True


[(0, 0),
 (1, 1),
 (2, 8),
 (3, 27),
 (4, 64),
 (5, 125),
 (6, 216),
 (7, 343),
 (8, 512),
 (9, 729),
 (10, 1000)]

In [43]:
# List mechanics
l = ['star', 1.5, 2, np.zeros((2,2))]     # Lists can store anything of any type

s = l                                     # This points to the same location in memory
l.append("DidItWork?")
print(s)                                  # Note that this was added to s as well
print()
s1 = l[:]                                 # OR list(l) Makes a copy
s1.pop(3)
print(s1)                                 # Note that these are no longer tied to each other. 
print(l)

print(s is l)                             #Do they point to same locaiton in memory? (Doesn't account for views)
print(s1 is l)


['star', 1.5, 2, array([[0., 0.],
       [0., 0.]]), 'DidItWork?']

['star', 1.5, 2, 'DidItWork?']
['star', 1.5, 2, array([[0., 0.],
       [0., 0.]]), 'DidItWork?']
True
False


In [27]:
# Linspace function. Used for floating-point sequences to get exact number in sequence. 
# 9 numbers between 0 and 2pi (so pi/4 increments)
np.linspace(0, 2*np.pi, 9)
print(np.linspace(0, 10, 5))
print(np.arange(0, 10.1, 2.5))

[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]


In [39]:
# Repeat Funciton
print(np.repeat("NANA", 8)) # 1D vector
print(np.repeat(np.array([[1,2],[3,4]]), 3,axis=0)) # Repeats the respective elements in the matrix
print()

#Vector of 1s
print(np.repeat(np.array([[1]]), 5,axis=0))
print(np.ones((5,1)))

#Array of Zeros
np.zeros((2,3))

# Matrix of 1s
np.repeat(1, 20).reshape(4,5) 

['NANA' 'NANA' 'NANA' 'NANA' 'NANA' 'NANA' 'NANA' 'NANA']
[[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]

[[1]
 [1]
 [1]
 [1]
 [1]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
#Math

# euler's number
np.exp(1)

# sin/cos
np.sin(np.pi)

a = np.arange(10)
a[[0,0,2,4]] += 10
print(a)

[10  1 12  3 14  5  6  7  8  9]


In [ ]:
# Loop logic
# break - exits first loop.
# Pass - DOes absolutely nothing

# For-Else. Else executes if break doesn't execute
for n in range(2, 10):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n//x)
            break
    else:
        # loop fell through without finding a factor
        print(n, 'is a prime number')